### ISSUE TITLE
IMDb Search

### ISSUE THREAD

**Issue by jevenski** [metesa/NFOGenerator#1]
Allows the user to search IMDb for the title and meta info of the movie which is to be filled in the text boxes in the general info section. (Using OMDb API)

**Comment by jevenski** [comment]
Simple IMDb search is added. 
TO-DO: handling search errors, such as "movie not found", "something went wrong", etc.

**Comment by metesa** [comment]
Backup info:
east suggested to add a button to search imdb info
www.imdb.com/find?s=title&q=the%20big%20bang%20theory
www.imdb.com/find?s=title&exact=true&q=the%20big%20bang%20theory

**Comment by jevenski** [comment]
Will work on it when facilitating the search function later. I'm thinking about opening a window to allow the user to choose the right one among the most relevant results. 

As for TV info, TheTVDB should be more suitable.
